oauth2_authorize:
  path: /%eccube_admin_route%/authorize2
  defaults: { _controller: Trikoder\Bundle\OAuth2Bundle\Controller\AuthorizationController::indexAction }

oauth2_token:
  path: /token
  defaults: { _controller: Trikoder\Bundle\OAuth2Bundle\Controller\TokenController::indexAction }
  methods: [POST]
