source "https://rubygems.org"

gem "minimal-mistakes-jekyll"
gem "liquid-c"

group :jekyll_plugins do
  gem "github-pages", ">= 224"
  gem "jekyll-feed"
  gem "jekyll-gist"
  gem "jekyll-include-cache"
  gem "jekyll-paginate"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end
